import Foundation
import SwiftUI

// MARK: - Meeting Memory
//
// The "daily love" layer. Meetings aren't isolated files — they're episodes in
// ongoing relationships (people) and recurring threads (topics/projects), and
// each one leaves commitments behind. This aggregates everything we already have
// on disk (transcript history + the per-transcript AI sidecars) into three views:
//
//   • Open action items across ALL meetings (the recurring chore the app removes)
//   • People — every person you've met, threaded with their meetings + open items
//   • Topics — recurring meeting titles, threaded the same way ("projects")
//
// Everything is on-device: it only reads files MindExtract already wrote. Nothing
// here is generated by re-running AI — it harvests the briefs/notes you already have.

/// Stable identity for an action item across rebuilds: its transcript + its text.
/// Lets completion state survive even as the in-memory list is rebuilt.
func actionItemKey(_ transcriptID: UUID, _ text: String) -> String {
    transcriptID.uuidString + "|" + text.lowercased().trimmingCharacters(in: .whitespacesAndNewlines)
}

struct TrackedActionItem: Identifiable, Hashable {
    let key: String
    var id: String { key }
    let text: String
    let transcriptID: UUID
    let transcriptTitle: String
    let date: Date          // the meeting's date — so we can say "3 days ago"
    var done: Bool
    var completedAt: Date?
}

/// Everything we know about meetings with one person — falls out of the attendee
/// + renamed-speaker data captured at record time. Zero manual data entry.
struct PersonThread: Identifiable, Hashable {
    let name: String
    var id: String { name.lowercased() }
    let meetings: [TranscriptionHistoryItem]   // newest first
    let openItems: [TrackedActionItem]
    var lastMet: Date? { meetings.first?.transcriptionDate }
    // Identity is the name — enough for NavigationStack values.
    static func == (l: PersonThread, r: PersonThread) -> Bool { l.id == r.id }
    func hash(into hasher: inout Hasher) { hasher.combine(id) }
    var initials: String {
        let parts = name.split(separator: " ")
        let first = parts.first?.first.map(String.init) ?? ""
        let last = parts.count > 1 ? (parts.last?.first.map(String.init) ?? "") : ""
        return (first + last).uppercased()
    }
}

/// A recurring meeting title ("Weekly sync", "Project X review") clustered across
/// dates — a pragmatic "project" view with no tagging required.
struct TopicThread: Identifiable, Hashable {
    let key: String
    var id: String { key }
    let title: String
    let meetings: [TranscriptionHistoryItem]   // newest first
    let openItems: [TrackedActionItem]
    var lastMet: Date? { meetings.first?.transcriptionDate }
    static func == (l: TopicThread, r: TopicThread) -> Bool { l.id == r.id }
    func hash(into hasher: inout Hasher) { hasher.combine(id) }
}

// MARK: - Completion state (persisted)

/// Remembers which action items the user has checked off, keyed by `actionItemKey`.
/// Stored separately from transcripts because an item's "done" status is a property
/// of the user's follow-through, not of the meeting.
@MainActor
final class ActionItemStateStore {
    static let shared = ActionItemStateStore()

    private var completed: [String: Date] = [:]
    private let fileURL: URL
    private let ioQueue = DispatchQueue(label: "com.mindact.mindextract.actionitems")

    private init() {
        let fm = FileManager.default
        let base = (try? fm.url(for: .applicationSupportDirectory, in: .userDomainMask, appropriateFor: nil, create: true))
            ?? fm.temporaryDirectory
        let dir = base.appendingPathComponent("MindExtract", isDirectory: true)
        if !fm.fileExists(atPath: dir.path) {
            try? fm.createDirectory(at: dir, withIntermediateDirectories: true)
        }
        fileURL = dir.appendingPathComponent("actionItemState.json")
        if let data = try? Data(contentsOf: fileURL),
           let decoded = try? JSONDecoder().decode([String: Date].self, from: data) {
            completed = decoded
        }
    }

    func isDone(_ key: String) -> Bool { completed[key] != nil }
    func completedAt(_ key: String) -> Date? { completed[key] }

    func set(_ key: String, done: Bool) {
        if done { completed[key] = Date() } else { completed.removeValue(forKey: key) }
        let snapshot = completed
        ioQueue.async { [fileURL] in
            if let data = try? JSONEncoder().encode(snapshot) {
                try? data.write(to: fileURL, options: .atomic)
            }
        }
    }
}

// MARK: - Aggregator

@MainActor
final class MeetingMemory: ObservableObject {
    static let shared = MeetingMemory()

    @Published private(set) var openActionItems: [TrackedActionItem] = []
    @Published private(set) var doneActionItems: [TrackedActionItem] = []
    @Published private(set) var people: [PersonThread] = []
    @Published private(set) var topics: [TopicThread] = []
    @Published private(set) var recentMeetings: [TranscriptionHistoryItem] = []

    private var lastSignature: Int = -1

    private init() {}

    /// Cheap to call on view appear — only does the work if the underlying history
    /// changed since the last rebuild.
    func refreshIfNeeded() {
        let history = TranscriptionHistoryManager.shared.history
        // Signature changes when items are added/removed/renamed; completion toggles
        // mutate in place so they don't need a signature bump.
        let sig = history.reduce(into: Hasher()) { h, item in
            h.combine(item.id); h.combine(item.title)
        }.finalize()
        guard sig != lastSignature else { return }
        rebuild()
    }

    func rebuild() {
        let history = TranscriptionHistoryManager.shared.history
        lastSignature = history.reduce(into: Hasher()) { h, item in
            h.combine(item.id); h.combine(item.title)
        }.finalize()

        var allItems: [TrackedActionItem] = []
        var personMeetings: [String: (display: String, items: [TranscriptionHistoryItem])] = [:]
        var topicMeetings: [String: (title: String, items: [TranscriptionHistoryItem])] = [:]
        var recents: [TranscriptionHistoryItem] = []

        // Newest first throughout.
        let sorted = history.sorted { $0.transcriptionDate > $1.transcriptionDate }

        for h in sorted {
            // Only meetings carry attendees/briefs. Treat unlabeled (legacy) items as
            // meetings too, since older recordings predate the source tag.
            let isMeeting = h.sourceType == .meeting || h.sourceType == nil
            guard isMeeting, h.fileExists else { continue }
            guard let sidecar = TranscriptAIStore.load(for: h.filePath) else { continue }

            // Action items
            for text in Self.extractActionItemTexts(sidecar) {
                let key = actionItemKey(h.id, text)
                allItems.append(TrackedActionItem(
                    key: key, text: text, transcriptID: h.id, transcriptTitle: h.title,
                    date: h.transcriptionDate,
                    done: ActionItemStateStore.shared.isDone(key),
                    completedAt: ActionItemStateStore.shared.completedAt(key)))
            }

            // People (attendees + renamed speakers)
            for name in Self.peopleNames(sidecar) {
                let id = name.lowercased()
                if personMeetings[id] == nil { personMeetings[id] = (name, []) }
                personMeetings[id]?.items.append(h)
            }

            // Topics (recurring titles)
            let tkey = Self.topicKey(h.title)
            if !tkey.isEmpty {
                if topicMeetings[tkey] == nil { topicMeetings[tkey] = (h.title, []) }
                topicMeetings[tkey]?.items.append(h)
            }

            // Recent recaps — only meetings that actually have a brief/summary.
            if recents.count < 6,
               sidecar.templateOutputs?[PromptTemplateLibrary.meetingBriefID.uuidString] != nil
                || sidecar.summary?.isEmpty == false {
                recents.append(h)
            }
        }

        let open = allItems.filter { !$0.done }.sorted { $0.date > $1.date }
        let done = allItems.filter { $0.done }.sorted { ($0.completedAt ?? $0.date) > ($1.completedAt ?? $1.date) }
        openActionItems = open
        doneActionItems = done

        // Map open items onto people/topics by their source transcript.
        let openByTranscript = Dictionary(grouping: open, by: { $0.transcriptID })

        people = personMeetings.values.map { entry in
            let ids = Set(entry.items.map(\.id))
            let items = ids.flatMap { openByTranscript[$0] ?? [] }.sorted { $0.date > $1.date }
            return PersonThread(name: entry.display, meetings: entry.items, openItems: items)
        }
        .sorted { ($0.lastMet ?? .distantPast) > ($1.lastMet ?? .distantPast) }

        topics = topicMeetings.values
            .filter { $0.items.count >= 2 }   // a single meeting isn't a "project"
            .map { entry in
                let ids = Set(entry.items.map(\.id))
                let items = ids.flatMap { openByTranscript[$0] ?? [] }.sorted { $0.date > $1.date }
                return TopicThread(key: Self.topicKey(entry.title), title: entry.title,
                                   meetings: entry.items, openItems: items)
            }
            .sorted { ($0.lastMet ?? .distantPast) > ($1.lastMet ?? .distantPast) }

        recentMeetings = recents
    }

    func toggle(_ item: TrackedActionItem) {
        let nowDone = !item.done
        ActionItemStateStore.shared.set(item.key, done: nowDone)
        // Mutate in place for a snappy UI, then re-derive the open/done split.
        func apply(_ list: inout [TrackedActionItem]) {
            if let i = list.firstIndex(where: { $0.key == item.key }) {
                list[i].done = nowDone
                list[i].completedAt = nowDone ? Date() : nil
            }
        }
        apply(&openActionItems); apply(&doneActionItems)
        let merged = (openActionItems + doneActionItems)
        openActionItems = merged.filter { !$0.done }.sorted { $0.date > $1.date }
        doneActionItems = merged.filter { $0.done }.sorted { ($0.completedAt ?? $0.date) > ($1.completedAt ?? $1.date) }
        rebuildPeopleTopicOpenCounts()
    }

    /// People/topic open-item lists reference open items — refresh them after a toggle
    /// without a full disk rescan.
    private func rebuildPeopleTopicOpenCounts() {
        let openByTranscript = Dictionary(grouping: openActionItems, by: { $0.transcriptID })
        people = people.map { p in
            let ids = Set(p.meetings.map(\.id))
            let items = ids.flatMap { openByTranscript[$0] ?? [] }.sorted { $0.date > $1.date }
            return PersonThread(name: p.name, meetings: p.meetings, openItems: items)
        }
        topics = topics.map { t in
            let ids = Set(t.meetings.map(\.id))
            let items = ids.flatMap { openByTranscript[$0] ?? [] }.sorted { $0.date > $1.date }
            return TopicThread(key: t.key, title: t.title, meetings: t.meetings, openItems: items)
        }
    }

    // MARK: Pre-meeting prep

    /// Past meetings + open items relevant to an upcoming meeting, matched by its
    /// attendees. Powers the "never walk in cold" prep card.
    func prep(forAttendees names: [String]) -> (meetings: [TranscriptionHistoryItem], openItems: [TrackedActionItem]) {
        let wanted = Set(names.flatMap { Self.matchTokens($0) }).subtracting(["you"])
        guard !wanted.isEmpty else { return ([], []) }
        let matched = people.filter { person in
            !Self.matchTokens(person.name).isDisjoint(with: wanted)
        }
        var seen = Set<UUID>()
        var meetings: [TranscriptionHistoryItem] = []
        for m in matched.flatMap(\.meetings).sorted(by: { $0.transcriptionDate > $1.transcriptionDate }) {
            if seen.insert(m.id).inserted { meetings.append(m) }
        }
        let mIds = Set(meetings.map(\.id))
        let items = openActionItems.filter { mIds.contains($0.transcriptID) }
        return (Array(meetings.prefix(5)), items)
    }

    // MARK: - Parsing helpers (free of UI / actor coupling)

    private static func matchTokens(_ name: String) -> Set<String> {
        Set(name.lowercased().split(whereSeparator: { !$0.isLetter }).map(String.init).filter { $0.count > 1 })
    }

    private static let defaultSpeakerLabels: Set<String> = ["you", "others", "unknown", "speaker", "guest"]

    private static func isDefaultLabel(_ s: String) -> Bool {
        let t = s.trimmingCharacters(in: .whitespaces).lowercased()
        if t.isEmpty { return true }
        if defaultSpeakerLabels.contains(t) { return true }
        // "Speaker 1", "Speaker 12"
        if t.range(of: #"^speaker\s*\d+$"#, options: .regularExpression) != nil { return true }
        return false
    }

    private static func peopleNames(_ sidecar: TranscriptAISidecar) -> [String] {
        var names: [String] = []
        var seen = Set<String>()
        func add(_ raw: String) {
            let n = raw.trimmingCharacters(in: .whitespaces)
            guard !isDefaultLabel(n) else { return }
            let k = n.lowercased()
            if seen.insert(k).inserted { names.append(n) }
        }
        (sidecar.speakerSuggestions ?? []).forEach(add)
        (sidecar.speakerNames ?? [:]).values.forEach(add)
        return names
    }

    private static let actionItemsAliases: Set<String> = [
        "action items", "åtgärdspunkter", "aktionspunkter", "att göra",
        "action points", "maßnahmen", "aufgaben", "tâches", "points d'action",
        "acciones", "tareas", "azioni", "punti d'azione"
    ]

    /// The action items for a transcript — prefer the standalone Action Items
    /// template, else the "## Action items" section of the Meeting Brief.
    private static func extractActionItemTexts(_ sidecar: TranscriptAISidecar) -> [String] {
        if let out = sidecar.templateOutputs?[PromptTemplateLibrary.actionItemsID.uuidString]?.text,
           !out.isEmpty {
            return parseActionItems(out)
        }
        if let brief = sidecar.templateOutputs?[PromptTemplateLibrary.meetingBriefID.uuidString]?.text {
            let section = briefSection(brief, "Action items")
            if !section.isEmpty { return parseActionItems(section) }
        }
        return []
    }

    /// Lines under a "## <header>" section, up to the next header (mirrors the Brief
    /// renderer, including localized-header fallback for Action items).
    private static func briefSection(_ text: String, _ header: String) -> String {
        var out: [String] = []
        var inSection = false
        for line in text.components(separatedBy: "\n") {
            if line.hasPrefix("## ") {
                let h = line.dropFirst(3).trimmingCharacters(in: .whitespaces)
                let isMatch = h.caseInsensitiveCompare(header) == .orderedSame
                    || (header == "Action items" && actionItemsAliases.contains(h.lowercased()))
                inSection = isMatch
                continue
            }
            if inSection { out.append(line) }
        }
        return out.joined(separator: "\n")
    }

    /// Bullet/numbered/checkbox list items, markers stripped. Skips "- None".
    static func parseActionItems(_ text: String) -> [String] {
        func clean(_ raw: String) -> String? {
            var s = raw.trimmingCharacters(in: .whitespaces)
            guard !s.isEmpty else { return nil }
            let markers = ["- [ ]", "- [x]", "* [ ]", "☐", "□", "•", "-", "*", "·"]
            for m in markers where s.hasPrefix(m) {
                s = String(s.dropFirst(m.count)).trimmingCharacters(in: .whitespaces); break
            }
            if let r = s.range(of: #"^\d{1,3}[.)]\s+"#, options: .regularExpression) {
                s = String(s[r.upperBound...]).trimmingCharacters(in: .whitespaces)
            }
            s = s.replacingOccurrences(of: "**", with: "")
            if s.isEmpty || s.hasPrefix("#") { return nil }
            if s.lowercased() == "none" || s.lowercased() == "n/a" { return nil }
            return s
        }
        let lines = text.components(separatedBy: .newlines)
        let markered = lines.filter { line in
            let t = line.trimmingCharacters(in: .whitespaces)
            return t.hasPrefix("-") || t.hasPrefix("*") || t.hasPrefix("•") || t.hasPrefix("·")
                || t.hasPrefix("☐") || t.hasPrefix("□")
                || t.range(of: #"^\d{1,3}[.)]\s+"#, options: .regularExpression) != nil
        }
        return markered.compactMap(clean).filter { $0.count > 2 }
    }

    /// Normalizes a meeting title into a clustering key: lowercased, with dates,
    /// numbers, weekday names and trailing punctuation stripped. "Weekly sync #12"
    /// and "Weekly sync — 2026-06-22" collapse to the same key.
    static func topicKey(_ title: String) -> String {
        var s = title.lowercased()
        // Remove ISO-ish dates and times.
        s = s.replacingOccurrences(of: #"\b\d{4}[-/]\d{1,2}[-/]\d{1,2}\b"#, with: "", options: .regularExpression)
        s = s.replacingOccurrences(of: #"\b\d{1,2}[:.]\d{2}\b"#, with: "", options: .regularExpression)
        // Weekday + month names (en + sv) that usually mark a specific occurrence.
        let calWords = ["monday","tuesday","wednesday","thursday","friday","saturday","sunday",
                        "måndag","tisdag","onsdag","torsdag","fredag","lördag","söndag",
                        "january","february","march","april","may","june","july","august",
                        "september","october","november","december",
                        "januari","februari","mars","april","maj","juni","juli","augusti","oktober"]
        var tokens = s.split(whereSeparator: { !$0.isLetter && !$0.isNumber }).map(String.init)
        tokens = tokens.filter { tok in
            if calWords.contains(tok) { return false }
            if tok.allSatisfy(\.isNumber) { return false }   // drop bare numbers (#12, week 3)
            return tok.count > 1
        }
        return tokens.joined(separator: " ")
    }
}
